package compliance

// Minimal placeholder types for compliance references
type ComplianceRequirement struct{}
type Control struct{}
type ComplianceStandard struct{}
type Procedure struct{}
type Document struct{}
type TrainingRequirement struct{}
type AuditRequirement struct{}
type ReportingRequirement struct{}
type Penalty struct{}
type Reference struct{}
type Regulation struct{}
type Policy struct{}
type EvidenceManager struct{}
type GapAnalysis struct{}
type MaturityAssessment struct{}
type RiskAssessmentEngine struct{}
type Mapping struct{}
type MaturityModel struct{}
type AssessmentCriteria struct{}
type Stakeholder struct{}
type ComplianceScoring struct{}
type ComplianceBenchmarking struct{}
type ComplianceRoadmap struct{}
type StakeholderManager struct{}
type ComplianceCommunication struct{}
type ComplianceWorkflow struct{}
type ApprovalEngine struct{}
type DocumentManager struct{}
type ComplianceManagerConfig struct{}
type AuditEngine struct{}
type AuditType struct{}
type AuditPlan struct{}
type AuditScope struct{}
type AuditMethodology struct{}
type AuditTeamMember struct{}
type AuditSchedule struct{}
type AuditProcedure struct{}
type AuditTest struct{}
type AuditSampling struct{}
type AuditEvidence struct{}
type AuditWorkpaper struct{}
type AuditFinding struct{}
type AuditObservation struct{}
type AuditRecommendation struct{}
type AuditReport struct{}
type AuditCommunication struct{}
type AuditRisk struct{}
type AuditControl struct{}
type AuditException struct{}
type AuditAnalytics struct{}
type AuditQuality struct{}
type AuditBudget struct{}
type AuditResource struct{}
type AuditTimeline struct{}
type AuditProgress struct{}
type AuditPerformance struct{}
type AuditStakeholder struct{}
type AuditApproval struct{}
type AuditFollowUp struct{}
type LessonLearned struct{}

