package infrastructure

// Minimal placeholder types for infrastructure zones
type GeoLocation struct{}
type ZoneCapacity struct{}
type ZoneUtilization struct{}
type ZonePerformance struct{}
type ZoneHealth struct{}
type ZoneResources struct{}
type ZoneNetworking struct{}
type ZoneStorage struct{}
type ZoneCompute struct{}
type SecurityGroup struct{}
type Subnet struct{}
type Instance struct{}
type Listener struct{}
type TargetGroup struct{}
type RoutingRule struct{}
type SSLCertificate struct{}
type SessionAffinity struct{}
type HealthCheck struct{}
type LBMonitoring struct{}
type Datacenter struct{}
type RegionCompliance struct{}
type RegionPricing struct{}
type Database struct{}
type Cache struct{}
type Queue struct{}
type LBMetrics struct{}
type AccessLogs struct{}
type ConnectionDraining struct{}
type DataResidency struct{}
type RegionCapacity struct{}
type RegionPerformance struct{}
type RegionSLA struct{}
type RegionDR struct{}
type RegionSecurity struct{}
type RegionMonitoring struct{}
type RegionHealth struct{}
type RegionUtilization struct{}
type RegionTraffic struct{}
type GeolocationService struct{}
type LatencyOptimizer struct{}
type RegionSelection struct{}
type TrafficRouting struct{}
type RegionFailover struct{}
type CrossRegionReplication struct{}
type GlobalConsistency struct{}
type RegionAnalytics struct{}
type Incident struct{}
type MaintenanceWindow struct{}
type RegionMigration struct{}
type RegionConfig struct{}
type CDNProvider struct{}
type EdgeResources struct{}
type EdgePerformance struct{}
type EdgeHealth struct{}
type EdgeUtilization struct{}
type EdgeTraffic struct{}
type BandwidthCapacity struct{}
type StorageCapacity struct{}

